### PR TITLE
#2147 - Student Application Updates: PD/ PPD Form Update on application - part time issue fix

### PR DESCRIPTION
**Pull request by ann-aot**
- While copying and pasting there was a filter for full-time in the new disability section, because of that the disability section was not showing for part-time applications.
- Full-time
image
image
- Part-time
image
image
- When we copy and paste an existing radio component, and if they have any input with the same value(key), then both inputs with the same value have the same HTML `id`. eg, there is a radio input question with 2 choices with value example 1.`yes` 2. `no`. and when we copy and paste this radio component to create a new question 2, with 2 choices with value 1. `yes` and 2. `ggg`. Then question 1 choice 1 and qn 2 choice 1 have the same HTML id, because when you select question 2 choice 1, then sometimes question 1 choice 1 is also selected. As a fix, I removed the copied radio component and added a new radio component for the question.
image

### CODE REVIEW

**Review by sh16011993 — APPROVED** [review]
LGTM @ann-aot 👍

**Review by andrewsignori-aot — APPROVED** [review]
Looks good 👍

**Review by dheepak-aot — APPROVED** [review]
Nice catch. Looks good 👍

**Review by guru-aot — APPROVED** [review]
LGTM, nice work @ann-aot

**Pull request merged**
