### PR TITLE
#2484 - Add year of study column to offering listing

### PR DESCRIPTION
**Pull request by andrepestana-aot**
- Added a column to the offering listing:
image

### CODE REVIEW

**Review by sh16011993 — APPROVED** [review]
LGTM 👍

**Review by dheepak-aot — APPROVED** [review]
Thanks for the quick update to ticket. Looks Good 👍

**Review by andrewsignori-aot — APPROVED** [review]
Thanks for taking care of it quickly, looks good 👍

**Review by lewischen-aot — APPROVED** [review]
LGTM 👍

**Review by guru-aot — APPROVED** [review]
LGTM

**Pull request merged**
