### PR TITLE
#2479 - Finastra - File name change

### PR DESCRIPTION
**Pull request by lewischen-aot**
- Change the PT eCert SEND file naming convention to: TPBC.EDU.NEW.PTCERTS.Dyyyyjjj.001

### CODE REVIEW

**Review by andrewsignori-aot — APPROVED** [review]
Nice work, first PR looks good 👍 🥳

**Review by ann-aot — APPROVED** [review]
👍 Good first task @lewischen-aot

**Review by dheepak-aot — APPROVED** [review]
Nice first PR. 👍

Looks good.

**Review by guru-aot — APPROVED** [review]
LGTM, nice work @lewischen-aot

**Pull request merged**
