### PR TITLE
#2349 - Clicking institution name in offering change request view should navigate to institution profile

### PR DESCRIPTION
**Pull request by sh16011993**
As a part of this PR, the following bug was fixed:

- [x] Clicking on the Institution Name does not navigate to the Institution Profile
- [x] Changed `institutionId`, `institutionName` and `locationName` properties from optional to mandatory in the DTOs.

**Issue:** The institution id was not being returned by the API and therefore clicking on the Institution Name did not navigate to the Institution Profile

**Fix:** The institution id was added to the `EducationProgramAPIOutDTO` and the web was adjusted to fix the issue.

Screenshot:

image

Clicking on the above highlighted Institution Name link takes to the below shown Institution Profile view.

image

### CODE REVIEW

**Review by andrewsignori-aot — APPROVED** [review]
Nice work, looks good 👍

**Review by andrepestana-aot — APPROVED** [review]
Looks good!

**Review by dheepak-aot — COMMENTED** [review]
LGTM 👍

**Review by dheepak-aot — APPROVED** [review]

**Review by ann-aot — APPROVED** [review]
👍

**Review by guru-aot — APPROVED** [review]
LGTM, nice work  @sh16011993

**Pull request merged**
