### PR TITLE
[API][SIMS-#1365] Soft delete part 1

### PR DESCRIPTION
**Pull request by henryoforeh-aot**
- Refactored code that was deleting record in institution_user_auth table to delete use soft delete.
- Added deletedAt property to  institution user auth model.
- Created migration scripts.

### CODE REVIEW

**Review by guru-aot — APPROVED** [review]
LGTM, Nice work @henryoforeh-aot

**Review by andrewsignori-aot — APPROVED** [review]
Nice work, these changes look good 👍 
There was one AC "Investigate using a centralized soft delete method (Short term timebox)" that was added due to a @dheepak-aot comment in a previous PR. Is there any output for it?

**Review by dheepak-aot — APPROVED** [review]
LGTM @henryoforeh-aot .

I had the same question what @andrewsignori-aot mentioned regarding the investigation on centralized soft delete which was mentioned in the story.

**Review by ann-aot — APPROVED** [review]
Good work @henryoforeh-aot 👍

**Pull request merged**
