### PR TITLE
[devops][SIMS #451] Node JS Upgrade to 16

### PR DESCRIPTION
**Pull request by dheepak-aot**
Upgrading NodeJS to version 16.

### CODE REVIEW

**Review by andrewsignori-aot — APPROVED** [review]
Looks good 👍

**Review by ann-aot — APPROVED** [review]
👍

**Review by guru-aot — CHANGES_REQUESTED** [review]
https://github.com/bcgov/SIMS/blob/main/docs/technologies-overview.md can we please update the readme too?

**Review by abschwenker — APPROVED** [review]

**Review by henryoforeh-aot — APPROVED** [review]

**Comment by dheepak-aot** [comment]
@guru-aot readme has been updated.

**Review by guru-aot — APPROVED** [review]
LGTM, thanks for the changes @dheepak-aot

**Pull request merged**
