### PR TITLE
#2518 - Add migration for disability status effective date

### PR DESCRIPTION
**Pull request by dheepak-aot**
## Add migration for disability status effective date

Add a column `disability_status_effective_date` to `sims.students`

### CODE REVIEW

**Review by guru-aot — APPROVED** [review]
LGTM, nice work @dheepak-aot

**Review by andrewsignori-aot — APPROVED** [review]
Looks good 👍

**Review by andrepestana-aot — APPROVED** [review]
👍 Looks good!

**Review by ann-aot — COMMENTED** [review]
👍

**Pull request merged**
