### PR TITLE
#2323 - Create notifications query error

### PR DESCRIPTION
**Pull request by andrewsignori-aot**
Fixed the query used by `createNotifications` that was throwing an error due to the incorrect object-query syntax.
This was impacting multiple restriction notifications such as:
- Add Provincial Restriction
- Temporary SIN
- Scholastic Standing
- Federal Restrictions

The application submission is now working as expected, validating and generating the error message.

image

Error on Add Provincial Restriction also fixed

image

image

### CODE REVIEW

**Review by guru-aot — APPROVED** [review]
LGTM, Nice work @andrewsignori-aot

**Review by andrepestana-aot — APPROVED** [review]
Looks good!

**Review by dheepak-aot — APPROVED** [review]
Looks Good 👍

**Review by ann-aot — APPROVED** [review]
👍

**Review by sh16011993 — APPROVED** [review]
Nice Work 👍 LGTM.

**Pull request merged**
