### PR TITLE
[web][api][OpenShift]Update Nodejs to version 16 and ssh2-sftp-client to 7.1.0

### PR DESCRIPTION
**Pull request by andrewsignori-aot**
- Updated Nodejs from 12 to 16. There were issues while migration from 12 to 16(slim) with some messages related to "missing python" (found [this discussion](https://github.com/nodejs/docker-node/issues/1385) about it also). So the version for DEV was changed to be the same used for Openshift. Please let me know if there is any concern or suggestions about it.
- There were also some issues related to reading the SFTP private key that has line breaks in the configuration ".env" file. This issue should not affect the application once deployed to Openshift because of the way it is being read from the secret file. It was affecting only local dev env while executing the API on docker. Please let me know if there is any concern or suggestions about it.
- Update ssh2 client from 6.0.1 to 7.1.0. As per the release notes "_This version of ssh2 is a complete re-write of the ssh2 library._" ([changes](https://github.com/theophilusx/ssh2-sftp-client#version-7x-changes))

### CODE REVIEW

**Review by guru-aot — APPROVED** [review]
LGTM, Does this have any features or enhancements we can use directly?

**Comment by andrewsignori-aot** [comment]
> LGTM, Does this have any features or enhancements we can use directly?

https://medium.com/the-node-js-collection/node-js-16-available-now-7f5099a97e70 😉

**Review by ann-aot — APPROVED** [review]
LGTM

**Review by abschwenker — APPROVED** [review]

**Review by dheepak-aot — APPROVED** [review]
LGTM. 👍

**Pull request merged**
