### PR TITLE
#1759 - MSFAA UI Changes for NOA - Fix form.io definition

### PR DESCRIPTION
**Pull request by andrewsignori-aot**
Removing extra "," that was causing a form.io deploying issue.

### CODE REVIEW

**Review by ann-aot — APPROVED** [review]
👍

**Review by andrepestana-aot — APPROVED** [review]
👍

**Review by sh16011993 — APPROVED** [review]
LGTM 👍

**Review by dheepak-aot — COMMENTED** [review]
👍

**Pull request merged**
