### PR TITLE
SIMS 190 -Part 1 - Refactoring interfaces in web into a common folder to avoid repeated uses across web code

### PR DESCRIPTION
**Pull request by 2011sandeepraj**
Part 2 of this ticket will be submitted via  different PR

### CODE REVIEW

**Review by fwpushan — CHANGES_REQUESTED** [review]
I think the root should be **types** and then you can put sub directory called contract (**types/contract**). Then we can put any non-contract type also in types folder.

**Review by andrewsignori-aot — COMMENTED** [review]
Nice work having this organized.
Is it possible to normalize the interface names? Some of them have the suffix "Contract" and some don't.

**Comment by andrewsignori-aot** [comment]
> Nice work having this organized.
> Is it possible to normalize the interface names? Some of them have the suffix "Contract" and some don't.

Nevermind about the "normalize" thing, it was my bad 👍

**Review by andrewsignori-aot — APPROVED** [review]
👍

**Review by fwpushan — APPROVED** [review]
👍

**Pull request merged**
