### PR TITLE
[Forms][SIMS-#1248] Client Name API

### PR DESCRIPTION
**Pull request by henryoforeh-aot**
Updated file upload URLs on form io. This was missed in the last PR.

### CODE REVIEW

**Review by ann-aot — APPROVED** [review]
👍

**Review by guru-aot — APPROVED** [review]
LGTM, nice work @henryoforeh-aot

**Review by andrewsignori-aot — APPROVED** [review]
Thanks for doing the fix @henryoforeh-aot we all forgot about these ones in the last PR. Looks good 👍

**Review by dheepak-aot — APPROVED** [review]
LGTM. Thanks for taking care of it @henryoforeh-aot

**Pull request merged**
