### PR TITLE
#2233 - Unable to view files Uploaded within App (Through Exception Path)

### PR DESCRIPTION
**Pull request by lewischen-aot**
-  Allow Ministry users to open files embedded within Student App
-  Allow students to view uploaded files

### CODE REVIEW

**Review by sh16011993 — APPROVED** [review]
👍

**Review by andrewsignori-aot — APPROVED** [review]
Nice catch, it looks good as per the tickets AC 👍 
Can you please create an E2E ticket to add some tests to validate file download from all applicable clients?

**Review by dheepak-aot — COMMENTED** [review]
Good Job! LGTM 👍

**Review by dheepak-aot — APPROVED** [review]

**Comment by lewischen-aot** [comment]
> Nice catch, it looks good as per the tickets AC 👍 Can you please create an E2E ticket to add some tests to validate file download from all applicable clients?

Sure. I'll create a ticket to add some tests to validate the file downloads.

**Pull request merged**
