### PR TITLE
[forms][SIMS #85]Update Designation Text

### PR DESCRIPTION
**Pull request by abschwenker**
- Update designation text
- Change component to scroll box and disabled by default
image
image

### CODE REVIEW

**Review by andrewsignori-aot — COMMENTED** [review]
Please check if the file is correctly configured as LF.

**Comment by abschwenker** [comment]
> Please check if the file is correctly configured as LF.

Updated

**Comment by dheepak-aot** [comment]
The overflow style can be eventually a custom css class.

**Review by andrewsignori-aot — APPROVED** [review]
Looks good 👍

**Review by dheepak-aot — APPROVED** [review]
LGTM 👍

**Review by henryoforeh-aot — APPROVED** [review]

**Pull request merged**
