### PR TITLE
#2036 - Fix search issue in the program data table that is using v-data-table search

### PR DESCRIPTION
**Pull request by ann-aot**
- Program table search fix
_screenshots_
image

### CODE REVIEW

**Review by andrewsignori-aot — APPROVED** [review]
👍

**Review by sh16011993 — APPROVED** [review]
👍

**Review by dheepak-aot — APPROVED** [review]

**Review by guru-aot — APPROVED** [review]
LGTM, nice work @ann-aot

**Review by andrepestana-aot — APPROVED** [review]
👍

**Pull request merged**
