### PR TITLE
#2522 - COE Disability Application Status description

### PR DESCRIPTION
**Pull request by andrepestana-aot**
COE Disability Application Status description: 
- "Assessment Includes disability funding types." (corresponds to option 1 in the student form)
- "No disability funding types included on assessment." (corresponds to option 2 or 3 in the student form)

image

### CODE REVIEW

**Review by dheepak-aot — APPROVED** [review]
Looks good. 👍

**Review by guru-aot — APPROVED** [review]
LGTM

**Review by sh16011993 — APPROVED** [review]
👍

**Review by lewischen-aot — APPROVED** [review]
LGTM 👍

**Review by andrewsignori-aot — APPROVED** [review]
Thanks for the quick change, looks good 👍

**Pull request merged**
