### PR TITLE
[formio][SIMS #1124]Change canada to Canada

### PR DESCRIPTION
**Pull request by andrewsignori-aot**
- Updated country dropdown code from _canada_ to _Canada_ to be displayed correctly in the UI;
- Changed some form conditions to display _Province_ or _Custom Country_ based on the dropdown selected code, previously there were some based on the _country_ that caused issues when the country code was renamed to Canada with the proper case;
- All files were formatted with Prettier and one changed from CRLF to LF.

The changes access all the files are pretty much the same. 

Below are the real changes sample:

image

image

### CODE REVIEW

**Review by henryoforeh-aot — APPROVED** [review]

**Comment by guru-aot** [comment]
Can you please check the formatting of the document? I feel the json is not formatted right @andrewsignori-aot

**Review by guru-aot — APPROVED** [review]
LGTM

**Review by ann-aot — APPROVED** [review]

**Comment by andrewsignori-aot** [comment]
> Can you please check the formatting of the document? I feel the json is not formatted right @andrewsignori-aot image

As we talked about in the chat, let's keep the Prettier as the default one.

**Review by dheepak-aot — APPROVED** [review]
LGTM @andrewsignori-aot

**Pull request merged**
