### PR TITLE
#2614 - PT Award Eligibility - BCAG

### PR DESCRIPTION
**Pull request by lewischen-aot**
- Updated awardEligibilityBCAG in parttime assessments for all program years
 - Adjusted E2E tests

Camunda Screenshot
Screenshot 2024-01-18 115806

### CODE REVIEW

**Review by guru-aot — APPROVED** [review]
LGTM, Nice work @lewischen-aot

**Review by sh16011993 — APPROVED** [review]
Nice work @lewischen-aot 👍

**Review by dheepak-aot — APPROVED** [review]
Nicely done @lewischen-aot . Looks Good 👍

**Review by andrewsignori-aot — APPROVED** [review]
Nice work, looks good 👍

**Pull request merged**
