### PR TITLE
#2373 - IER fix allow zero grants

### PR DESCRIPTION
**Pull request by dheepak-aot**
## IER Fix allow zero grants
 - [x] Add initial value to reduce function
 - [x] Test the fix by creating an application submitted for `BC Private` (any non BC Public institution) and applicant income as $100000
image

### CODE REVIEW

**Review by andrepestana-aot — APPROVED** [review]
👍

**Review by andrewsignori-aot — APPROVED** [review]
Looks good 👍

**Review by ann-aot — APPROVED** [review]
👍

**Review by sh16011993 — APPROVED** [review]
👍

**Pull request merged**
