### PR TITLE
[Web][SIMS-#1435]-Removed max-width and min-width as it is in common component

### PR DESCRIPTION
**Pull request by guru-aot**
Removed max-width and min-width as it is in common modal-dailog-base component

### CODE REVIEW

**Review by andrewsignori-aot — APPROVED** [review]
Thanks for doing the changes, looks good 👍

**Review by ann-aot — COMMENTED** [review]
@guru-aot I see its removed from the customer modal. but I didn't see it added to the custom component

**Comment by guru-aot** [comment]
> @guru-aot I see its removed from the customer modal. but I didn't see it added to the modal-dailog-base component

Its added in the previous PR @ann-aot

**Review by ann-aot — APPROVED** [review]
👍

**Pull request merged**
