### PR TITLE
#2300 - Update institution hyperlinks (#2400)

### PR DESCRIPTION
**Pull request by dheepak-aot**
## Update institution hyperlinks
 Cherry pick commit from main branch

### CODE REVIEW

**Review by andrewsignori-aot — APPROVED** [review]
Looks good 👍

**Review by guru-aot — APPROVED** [review]
LGTM

**Review by ann-aot — APPROVED** [review]
👍

**Review by andrepestana-aot — APPROVED** [review]
👍

**Review by sh16011993 — APPROVED** [review]
👍

**Comment by HRAGANBC** [comment]
Reviewed and signed off by Hugh on October 12. Everything A-OK. Thanks

**Pull request merged**
