### PR TITLE
[api][SIMS #766]Remove SFAS archive DB

### PR DESCRIPTION
**Pull request by andrewsignori-aot**
- Removed the sfas_db from local development resources;
- Changed the PD status check during student creation to get the value from the new SFAS tables;

### CODE REVIEW

**Review by abschwenker — APPROVED** [review]
LGTM - please make you completed a search for "sfas_db" "SFASDB" " "sfasdb" "ARCHIVE_DB" "ArchiveDb" to make sure they are all removed. Thanks!

**Comment by andrewsignori-aot** [comment]
> LGTM - please make you completed a search for "sfas_db" "SFASDB" " "sfasdb" "ARCHIVE_DB" "ArchiveDb" to make sure they are all removed. Thanks!

I did it and found just one comment that is changed now 😉

**Review by ann-aot — APPROVED** [review]
LGTM 👍

**Review by guru-aot — APPROVED** [review]
LGTM, Nice work @andrewsignori-aot

**Review by dheepak-aot — APPROVED** [review]
LGTM. 👍

**Pull request merged**
