### PR TITLE
#2150 - TESTING BUG - Unable to search student in the Support user portal (Parent/partner declaration portal)

### PR DESCRIPTION
**Pull request by ann-aot**
- Partner and partner When searching for the student application, I couldn't find any issue in my local, As discussed in the call, look like the loading issue mentioned in the ticket was due to point 4.
- Supporting partner data submission was failing - fixed
- Did an overall smoke test in the supporting user portal - everything looks fine.
- Supporting user form was not correct in TEST db, updated it
image
- Fixed a small UI issue - Once you search for an existing application and then try to search for a nonexisting application the form's Next step  and back btn was still visible
**Issue**
image
**Fix**
image

**Screenshots**
image
image

### CODE REVIEW

**Review by dheepak-aot — APPROVED** [review]
Looks good 👍Thanks for doing additional refactors.

**Review by andrewsignori-aot — APPROVED** [review]
Nice work and thanks for the navigation fix and reactors. Looks good 👍

**Review by sh16011993 — APPROVED** [review]
Looks good 👍

**Review by guru-aot — APPROVED** [review]
Great work @ann-aot

**Pull request merged**
