### PR TITLE
#1966 - Update user to nonroot user 1001

### PR DESCRIPTION
**Pull request by sh16011993**
In this PR, updated user to nonroot user 1001 for queue-consumer, api, workers and db-migration

### CODE REVIEW

**Review by ann-aot — APPROVED** [review]
Good to know,  `USER 1001: this is a non-root user UID. `
LGTM 👍

**Review by dheepak-aot — APPROVED** [review]
LGTM 👍

**Review by andrepestana-aot — APPROVED** [review]
👍

**Review by guru-aot — APPROVED** [review]
LGTM, nice work @sh16011993

**Pull request merged**
