### PR TITLE
#1957 - Ministry - Build out the ministry homepage

### PR DESCRIPTION
**Pull request by ann-aot**
- Updated ministry dashboard
- _screenshots_
image
image
image
image
image

### CODE REVIEW

**Review by andrewsignori-aot — APPROVED** [review]
The UI looks great. Looks good to me 👍

**Review by guru-aot — APPROVED** [review]
LGTM, nice work @ann-aot

**Review by dheepak-aot — APPROVED** [review]
Looks great 👍

**Review by sh16011993 — APPROVED** [review]
LGTM 👍. Nice work @ann-aot

**Pull request merged**
